import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'
import Product_Feed from './../components/Product_Feed';
export default function Home({products}) {
  return (
    <div className=''>
      <Head>
        <title>Not Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='max-w-screen-2xl mx-auto'>
      <Hero/>
        <Product_Feed
        products ={products}
        />
      </main>
      
    </div>
  )
}

export async function getServerSideProps(context){
  const products = await fetch('https://fakestoreapi.com/products').then((res)=>res.json())
  return {
     props:{
       products,
  }
}
} 